Repository maestro3517/FlutterQRApp, pull requests merged in 2022-07, with the labels that each got.

#21 20 refactor qr scanner page
  android/app/build.gradle
  lib/httpClient.dart
  lib/widgets/WAQrScannerScreen.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, UI, API

#22 18 implement new landing page
  lib/httpClient.dart
  lib/login.dart
  lib/widgets/LandingPage.dart
  lib/widgets/QRDataDisplay.dart
  lib/widgets/SplashScreen.dart
  lib/widgets/WAQrScannerScreen.dart
Labels: enhancement, UI

#23 19 refactor details page
  android/app/build.gradle
  lib/constants.dart
  lib/httpClient.dart
  lib/login.dart
  lib/utils/AppColors.dart
  lib/utils/AppConstant.dart
  lib/utils/AppWidget.dart
  lib/widgets/LandingPage.dart
  lib/widgets/QRDataDisplay.dart
  lib/widgets/SplashScreen.dart
  lib/widgets/WAQrScannerScreen.dart
  pubspec.lock
  pubspec.yaml
Labels: UI, API
